"""OTel span 名与属性 key。禁止在其它模块散落字符串。"""

TASK = "labhandler.task"
AGENT = "labhandler.agent"
TURN = "labhandler.turn"
CONTEXT_BUILD = "labhandler.context_build"
LLM = "labhandler.llm"
TOOL = "labhandler.tool"
GUARDRAIL = "labhandler.guardrail"
STAGNATION = "labhandler.stagnation"
HANDOFF = "labhandler.handoff"

ATTR_TASK_ID = "labhandler.task_id"
ATTR_AGENT = "labhandler.agent_name"
ATTR_MODEL = "gen_ai.request.model"
ATTR_TOOL = "labhandler.tool_name"
ATTR_ERROR_CLASS = "labhandler.error_class"
ATTR_TOKENS_IN = "gen_ai.usage.input_tokens"
ATTR_TOKENS_OUT = "gen_ai.usage.output_tokens"
ATTR_TOKENS_REASONING = "labhandler.usage.reasoning_tokens"
ATTR_OUTCOME = "labhandler.outcome"
