"""Span 名、observation 类型与属性 key。其它模块只引用本文件常量。"""

# ── span 名 ────────────────────────────────────────────
RUN = "labhandler.run"
TASK = "labhandler.task"
AGENT = "labhandler.agent"
TURN = "labhandler.turn"
CONTEXT_BUILD = "labhandler.context_build"
COMPACT = "labhandler.compact"
LLM = "labhandler.llm"
TOOL = "labhandler.tool"
GUARDRAIL = "labhandler.guardrail"
STEP = "labhandler.step"
JUDGE = "labhandler.judge"
ACCEPT = "labhandler.accept"

# ── 点事件名 ───────────────────────────────────────────
EV_RETRY = "labhandler.retry"
EV_STAGNATION = "labhandler.stagnation"
EV_HANDOFF = "labhandler.handoff"
EV_DECISION = "labhandler.decision"
EV_STEP_ERROR = "labhandler.step_error"

# ── observation 类型（Langfuse as_type）────────────────
KIND_SPAN = "span"
KIND_AGENT = "agent"
KIND_CHAIN = "chain"
KIND_TOOL = "tool"
KIND_GENERATION = "generation"
KIND_GUARDRAIL = "guardrail"
KIND_EVALUATOR = "evaluator"

# ── 属性 key ───────────────────────────────────────────
ATTR_RUN_ID = "labhandler.run_id"
ATTR_THREAD_ID = "labhandler.thread_id"
ATTR_TASK_ID = "labhandler.task_id"
ATTR_TASK_KIND = "labhandler.task_kind"
ATTR_PARENT_TASK_ID = "labhandler.parent_task_id"
ATTR_ASSIGNMENT_ID = "labhandler.assignment_id"
ATTR_DOMAIN = "labhandler.domain"
ATTR_STEP_GOAL = "labhandler.step_goal"
ATTR_AGENT = "labhandler.agent_name"
ATTR_PERMISSION = "labhandler.permission"
ATTR_STEP = "labhandler.step"
ATTR_STEP_BUDGET = "labhandler.step_budget"

ATTR_MODEL = "gen_ai.request.model"
ATTR_TOKENS_IN = "gen_ai.usage.input_tokens"
ATTR_TOKENS_OUT = "gen_ai.usage.output_tokens"
ATTR_TOKENS_REASONING = "labhandler.usage.reasoning_tokens"
ATTR_FINISH_REASON = "gen_ai.response.finish_reason"

ATTR_TOOL = "labhandler.tool_name"
ATTR_TOOL_ALLOWED = "labhandler.tool_allowed"
ATTR_ERROR_CLASS = "labhandler.error_class"
ATTR_OUTCOME = "labhandler.outcome"

ATTR_DECISION = "labhandler.decision"
ATTR_REASON = "labhandler.reason"
ATTR_ATTEMPT = "labhandler.attempt"
ATTR_DELAY_S = "labhandler.delay_s"
ATTR_SIGNAL = "labhandler.signal"
ATTR_FROM = "labhandler.from"
ATTR_TO = "labhandler.to"

ATTR_TOKENS_BEFORE = "labhandler.context.tokens_before"
ATTR_TOKENS_AFTER = "labhandler.context.tokens_after"
ATTR_TURNS_KEPT = "labhandler.context.turns_kept"
ATTR_TURNS_SUMMARIZED = "labhandler.context.turns_summarized"
ATTR_COMPACTED = "labhandler.context.compacted"
ATTR_FORGET_CLEARED = "labhandler.context.forget_cleared"

ATTR_GATE_STATE = "labhandler.gate.state"
ATTR_GATE_PASSED = "labhandler.gate.passed"
ATTR_GATE_FAILED = "labhandler.gate.failed"
ATTR_GATE_EXIT = "labhandler.gate.exit_code"

ATTR_WAVE_SIZE = "labhandler.step.workers"
